apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-moon
  namespace: moon
spec:
  replicas: 7
  selector:
    matchLabels:
      app: web-moon
  template:
    metadata:
      labels:
        app: web-moon
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: web-moon-html
              mountPath: /usr/share/nginx/html
              readOnly: true
      volumes:
        - name: web-moon-html
          configMap:
            name: configmap-web-moon-html
            items:
              - key: index.html
                path: index.html
