apiVersion: v1
kind: Pod
metadata:
  name: web-moon
  namespace: moon
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: web-moon-html
          mountPath: /usr/share/nginx/html
          readOnly: true
  volumes:
    - name: web-moon-html
      configMap:
        name: configmap-web-moon-html
        items:
          - key: index.html
            path: index.html
