apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: manager-api-svc
  name: manager-api-svc
  namespace: mars
spec:
  ports:
  - name: 4444-80
    port: 4444
    protocol: TCP
    targetPort: 80
  selector:
    app: manager-api-svc
  type: ClusterIP
status:
  loadBalancer: {}
