apiVersion: apps/v1
kind: Deployment
metadata:
  name: cleaner-con
  namespace: mercury
  labels:
    app: cleaner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cleaner
  template:
    metadata:
      labels:
        app: cleaner
    spec:
      containers:
        - name: cleaner-con
          image: alpine:latest
          command: ['sh', '-c', 'while true; do echo "logging" >> /opt/cleaner.log; sleep 1; done']
          volumeMounts:
            - name: data
              mountPath: /opt
      initContainers:
        - name: logger-con
          image: busybox:1.31.0
          restartPolicy: Always
          command: ['sh', '-c', 'tail -F /opt/cleaner.log']
          volumeMounts:
            - name: data
              mountPath: /opt
      volumes:
        - name: data
          emptyDir: {}
